### ISSUE TITLE
Deserialization fails with response from google knowledge graph.

### ISSUE THREAD

**Issue by fanavarro** [google/schemaorg-java#3]
Hi, I'm developing a project that must be able to perform a search against the google knowledge graph api, which returns a json-ld with the vocabulary from schema.org. I thought that schemaorg-java library would fit perfectly to get java objects from the google knowledge graph response but it is failing.

I think the reason is that google knowledge graph response returns the @type field as a list and schemaorg-java is expecting a single value.

For example, if I search "Taylor Swift", restricting the number of results to 2, I obtain the following response from google api:

```
{
  "@context": {
    "@vocab": "http://schema.org/",
    "goog": "http://schema.googleapis.com/",
    "EntitySearchResult": "goog:EntitySearchResult",
    "detailedDescription": "goog:detailedDescription",
    "resultScore": "goog:resultScore",
    "kg": "http://g.co/kg"
  },
  "@type": "ItemList",
  "itemListElement": [
    {
      "@type": "EntitySearchResult",
      "result": {
        "@id": "kg:/m/0dl567",
        "name": "Taylor Swift",
        "@type": [
          "Thing",
          "Person"
        ],
        "description": "American singer-songwriter",
        "image": {
          "contentUrl": "http://t0.gstatic.com/images?q=tbn:ANd9GcST848UJ0u31E6aoQfb2nnKZFyad7rwNF0ZLOCACGpu4jnboEzV",
          "url": "https://en.wikipedia.org/wiki/Begin_Again_(Taylor_Swift_song)",
          "license": "http://creativecommons.org/licenses/by/2.0"
        },
        "detailedDescription": {
          "articleBody": "Taylor Alison Swift is an American singer-songwriter. One of the most popular contemporary female recording artists, she is known for narrative songs about her personal life, which has received much media attention.\n",
          "url": "https://en.wikipedia.org/wiki/Taylor_Swift",
          "license": "https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License"
        },
        "url": "http://taylorswift.com/"
      },
      "resultScore": 874.928711
    },
    {
      "@type": "EntitySearchResult",
      "result": {
        "@id": "kg:/m/03g7rsz",
        "name": "Taylor Swift",
        "@type": [
          "MusicAlbum",
          "Thing"
        ],
        "description": "Studio album by Taylor Swift",
        "detailedDescription": {
          "articleBody": "Taylor Swift is the debut studio album by American singer-songwriter Taylor Swift, released on October 24, 2006, by Big Machine Records. Swift was 16 years old at the time of the album's release and wrote its songs during her freshman year of high school. Swift has writing credits on all of the album's songs, including those co-written with Liz Rose. Swift experimented with several producers, ultimately choosing Nathan Chapman, who had produced her demo album. ",
          "url": "https://en.wikipedia.org/wiki/Taylor_Swift_(album)",
          "license": "https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License"
        }
      },
      "resultScore": 523.882324
    }
  ]
}
```
Schemaorg-java does not suppor @vocab tag, so I compact the response, obtaining the following:

```
{
  "@type" : "http://schema.org/ItemList",
  "http://schema.org/itemListElement" : [ {
    "@type" : "http://schema.googleapis.com/EntitySearchResult",
    "http://schema.googleapis.com/resultScore" : 874.928711,
    "http://schema.org/result" : {
      "@id" : "http://g.co/kg/m/0dl567",
      "@type" : [ "http://schema.org/Thing", "http://schema.org/Person" ],
      "http://schema.googleapis.com/detailedDescription" : {
        "http://schema.org/articleBody" : "Taylor Alison Swift is an American singer-songwriter. One of the most popular contemporary female recording artists, she is known for narrative songs about her personal life, which has received much media attention.\n",
        "http://schema.org/license" : "https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License",
        "http://schema.org/url" : "https://en.wikipedia.org/wiki/Taylor_Swift"
      },
      "http://schema.org/description" : "American singer-songwriter",
      "http://schema.org/image" : {
        "http://schema.org/contentUrl" : "http://t0.gstatic.com/images?q=tbn:ANd9GcST848UJ0u31E6aoQfb2nnKZFyad7rwNF0ZLOCACGpu4jnboEzV",
        "http://schema.org/license" : "http://creativecommons.org/licenses/by/2.0",
        "http://schema.org/url" : "https://en.wikipedia.org/wiki/Begin_Again_(Taylor_Swift_song)"
      },
      "http://schema.org/name" : "Taylor Swift",
      "http://schema.org/url" : "http://taylorswift.com/"
    }
  }, {
    "@type" : "http://schema.googleapis.com/EntitySearchResult",
    "http://schema.googleapis.com/resultScore" : 523.882324,
    "http://schema.org/result" : {
      "@id" : "http://g.co/kg/m/03g7rsz",
      "@type" : [ "http://schema.org/MusicAlbum", "http://schema.org/Thing" ],
      "http://schema.googleapis.com/detailedDescription" : {
        "http://schema.org/articleBody" : "Taylor Swift is the debut studio album by American singer-songwriter Taylor Swift, released on October 24, 2006, by Big Machine Records. Swift was 16 years old at the time of the album's release and wrote its songs during her freshman year of high school. Swift has writing credits on all of the album's songs, including those co-written with Liz Rose. Swift experimented with several producers, ultimately choosing Nathan Chapman, who had produced her demo album. ",
        "http://schema.org/license" : "https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License",
        "http://schema.org/url" : "https://en.wikipedia.org/wiki/Taylor_Swift_(album)"
      },
      "http://schema.org/description" : "Studio album by Taylor Swift",
      "http://schema.org/name" : "Taylor Swift"
    }
  } ]
}
```
then, when I tried to get a list of thing by deserializing this Json-ld string, I get the following exception:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 8 column 18 path $.http://schema.org/itemListElement[0].http://schema.org/result.@type
	at com.google.gson.Gson.fromJson(Gson.java:899)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.schemaorg.JsonLdSerializer.deserialize(JsonLdSerializer.java:152)
	at es.um.es.sessamo.sessamo_model.GoogleKnowledgeGrapthTest.test2(GoogleKnowledgeGrapthTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 8 column 18 path $.http://schema.org/itemListElement[0].http://schema.org/result.@type
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readObject(JsonLdSerializer.java:431)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readInternal(JsonLdSerializer.java:593)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readObject(JsonLdSerializer.java:438)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readInternal(JsonLdSerializer.java:593)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readArray(JsonLdSerializer.java:612)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readInternal(JsonLdSerializer.java:596)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.readObject(JsonLdSerializer.java:438)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.read(JsonLdSerializer.java:408)
	at com.google.schemaorg.JsonLdSerializer$JsonLdTypeAdapter.read(JsonLdSerializer.java:162)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	... 28 more
```

Is there any way to deal with this?

Thanks in advance and best regards.

**Comment by danbri** [comment]
I have just taken over as admin/caretaker for this project. I don't expect your issue to be actively addressed, and so will close it here. There are other JSON-LD libraries that are more actively maintained, and for this case there is limited value in using a Schema.org-centric wrapper.
